name: Build CI

on:
  push:
    branches:
      - exiled
  pull_request:
    branches:
      - exiled
env:
  EXILED_REFERENCES_URL: https://misaka-zerotwo.github.io/SL-References/Dev.zip
  EXILED_REFERENCES_PATH: ${{ github.workspace }}/References

jobs:
  build-win:
    runs-on: windows-latest
    steps:
      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1.1.3
        with:
          # Folder location of where vswhere.exe is located if a self-hosted agent
          # vswhere-path: # optional
          # Version of Visual Studio to search; defaults to latest if not specified
          # vs-version: # optional
          # Enable searching for pre-release versions of Visual Studio/MSBuild
          vs-prerelease: false # optional
          # The preferred processor architecture of MSBuild. Can be either "x86" or "x64". "x64" is only available from Visual Studio version 17.0 and later.
          msbuild-architecture: x64
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      - uses: actions/checkout@v2.3.4

      - name: Get references
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri ${{ env.EXILED_REFERENCES_URL }} -OutFile ${{ github.workspace }}/References.zip
          Expand-Archive -Path References.zip -DestinationPath ${{ env.EXILED_REFERENCES_PATH }}

      - name: Restore Packages
        run: nuget restore SpectatorList.sln

      - name: Build
        env:
          EXILED_REFERENCES: ${{ env.EXILED_REFERENCES_PATH }}
        shell: pwsh
        run: |
          msbuild.exe SpectatorList.sln /p:Configuration="Release" /p:Platform="Any CPU"
      - uses: ncipollo/release-action@v1.13.0
        with:
          artifacts: "SpectatorList/bin/Release/SpectatorList.dll"
          generateReleaseNotes: false
          makeLatest: true
          token: ${{ secrets.GITHUB_TOKEN }}
          commit: master
          name: "${{ github.event.head_commit.message }} - ${{ github.sha }}"
          tag: "${{ github.run_id }}"
